name: Building Master
on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      configuration:
        description: "Build configuration"
        type: choice
        required: true
        default: Release
        options:
          - Debug
          - Release
      runtime:
        description: "Target runtime"
        type: choice
        required: true
        default: win-x64
        options:
          - win-x64
          - linux-x64
          - linux-arm64
      run_tests:
        description: "Run tests"
        type: boolean
        required: true
        default: true

jobs:
  setup:
    if: github.repository_owner == 'Jaxx7594'
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

  build:
    needs: setup
    runs-on: [self-hosted, linux]
    steps:
      - name: Build
        run: dotnet build Nitrox.Launcher/Nitrox.Launcher.csproj -c ${{ inputs.configuration }} -r ${{ inputs.runtime }}

  test:
    if: ${{ inputs.run_tests }}
    needs: build
    runs-on: [self-hosted, linux]
    steps:
      - name: Run Tests
        continue-on-error: true
        run: dotnet test Nitrox.Test/Nitrox.Test.csproj --logger trx --results-directory "test_results"

      - name: Upload Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@3a74b2957438d0b6e2e61d67b05318aa25c9e6c6 # v2.20.0
        if: (!cancelled())
        with:
          files: |
            test_results/*.trx
